### ISSUE TITLE
Failed to Download TNM Dataset

### ISSUE THREAD

**Issue by ThomasThelen** [blake-regalia/usgs-triplifier#3]
While running the triplifier I ran into a few small (related) issues. The issue probably lies with fetching the nhd data. In the logs below, you can see that the first error has to do with the download (I think of this dataset). Towards the end you can see where things fail when the file isn't found. While the triplifier was running with usgs data I inspected the container and confirmed that `inputs/nhd ` in fact hadn't been created.

### To Reproduce
1. Clone the repo
2. Docker build it
3. Docker run it
4. See output similar to that below

### Log

```
thomas usgs-triplifier % docker run 3e2b0c758b0f

> usgs-triplifier@1.0.0 all /src/app
> npm run download-gnis && npm run tnm && npm run gnis && npm run nhd


> usgs-triplifier@1.0.0 download-gnis /src/app
> ./tools/download-gnis.sh

/src/app /src/app/tools
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 47538  100 47538    0     0  81496      0 --:--:-- --:--:-- --:--:-- 81540
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 81.7M  100 81.7M    0     0  1210k      0  0:01:09  0:01:09 --:--:-- 1313k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 37.3M  100 37.3M    0     0  1072k      0  0:00:35  0:00:35 --:--:-- 1354k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6776k  100 6776k    0     0  1052k      0  0:00:06  0:00:06 --:--:-- 1157k
/src/app/tools

> usgs-triplifier@1.0.0 tnm /src/app
> ./tools/download-tnm.sh

/src/app /src/app/tools
/src/app/lib/tnm/download.js:56
				a_rows.map((h_row) => async () => {
				       ^

TypeError: Cannot read property 'map' of undefined
    at /src/app/lib/tnm/download.js:56:12
    at Parser.<anonymous> (/src/app/node_modules/csv-parse/lib/index.js:1011:7)
    at Parser.emit (events.js:327:22)
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at onwriteError (_stream_writable.js:411:3)
    at processTicksAndRejections (internal/process/task_queues.js:86:21)
/src/app/tools

> usgs-triplifier@1.0.0 gnis /src/app
> ./tools/triplify-gnis.sh

/src/app /src/app/tools
parsing GOVT_UNITS_20210501.txt

states.json
parsing NationalFile_20210501.txt
./tools/triplify-gnis.sh: line 4:    87 Killed                  node --max-old-space-size=8192 ./lib/gnis/$1.js
parsing AllNames_20210501.txt
./tools/triplify-gnis.sh: line 4:    98 Killed                  node --max-old-space-size=8192 ./lib/gnis/$1.js
parsing Feature_Description_History_20210501.txt


all done
/src/app/tools

> usgs-triplifier@1.0.0 nhd /src/app
> ./tools/triplify-nhd.sh

/src/app /src/app/tools
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/src/app/data/input/nhd/*.zip'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:163:14
    at FSReqCallback.oncomplete (fs.js:159:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/src/app/data/input/nhd/*.zip'
}
/src/app/tools
```

**Comment by ThomasThelen** [comment]
I retested this issue and believe that it's resolved. I've attached a screenshot for proof that the large nhd dataset was in fact downloaded.

<img width="580" alt="Screen Shot 2021-05-29 at 9 06 11 AM" src="https://user-images.githubusercontent.com/9289652/120077106-9210d400-c05d-11eb-92a5-702fb2e751e0.png">

Note that there is roughly 1gb of triples produced-if that seems right to you, then this code base seems to be working perfectly.
